pipeline:
variables:
  GIT_STRATEGY: clone
  GIT_CHECKOUT: "true"
 agent : any
 stages:
  - stage: Checkout
    steps:
     - git "https://github.com/effortlessdevsec/demoexpress.git"
  - stage : Build
    steps :  
     - echo 'building and installing all dependencies'
     - sh ' npm i '
  - stage : SAST
    parallel:
     - stage : SCA
       steps :
        - echo 'running sca scan'
        - sh '''ls '''
        - sh ''' snyk test "$(pwd)"  '''
