pipeline:
 agent : any
 stages:
  - stage : Build
    steps :  
     - echo 'building and installing all dependencies'
     - sh ' npm i '
  - stage : SAST
    parallel:
     - stage : SCA
       steps :
        - sh 'ls'
