pipeline:
 agent : any
 environment:
  defect_dojo: credentials('DEFECT_DOJO')
 stages:
  - stage: Checkout
    steps:
     - git 'https://github.com/effortlessdevsec/demoexpress.git'
  - stage : Build
    steps :  
     - echo 'building and installing all dependencies'
     - sh ' npm i '
  - stage : SAST
    parallel:
     - stage : SCA
       steps :
        - echo 'running sca scan'
        - sh '''ls '''
        - sh ''' snyk test "$(pwd)"  '''
     - stage : SCS
       steps:
         - echo 'running semgrep scan'
         - sh '''    semgrep --config "p/nodejsscan" "$(pwd)"  '''

 post:
   failed: error in pipeline
   always: 
     - echo  "hello success pipeline"
     - sh ''' curl --location http://localhost:8080/api/v2/reimport-scan/ \ --header "Authorization: Token ${DEFECT_DOJO}" \
                                             --form 'engagement_name="SAST"' \
                                             --form 'verified="true"' \
                                             --form 'active="true"' \
                                             --form 'lead="1"' \
                                             --form 'tags="test"' \
                                             --form 'scan_type="Snyk Scan"' \
                                             --form 'minimum_severity="Info"' \
                                             --form 'close_old_findings="false"' \
                                             --form "file=@$PWD/SNYK.json" \
                                             --form 'product_name="NINZASWORKOUT"' \
                                             --form 'test_title="SCA"'  '''
    
     
  
         
       
