pipeline:
 agent : any
 stages:
  - stage : Build
    steps :  
     - echo 'building and installing all dependencies'
     - sh ' npm i '
  - stage : SAST
    parallel:
     - stage : SCA
       steps :
        - echo 'running sca scan'
        - sh '''ls '''
        - sh ''' snyk test "$(pwd)"  '''
